language: ruby
rvm:
- 2.1.3

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - rake rspec:features

bundler_args: --binstubs=./bundler_stubs
